[package]
name = "alias-rs"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/nomyfan/alias-rs"

[dependencies]
anyhow = "1"
dirs = "5"
serde = { version = "1", features = ["std", "derive"] }
toml = "0.8.6"

[[bin]]
name = "als"
path = "src/main.rs"
